config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#index"
  # get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #使用 collection 要對複數資料做操作
  resources :tasks do
    collection do
      get :search
    end
  end

  resources :users, controller: 'users'
  namespace :admin do
    root 'user#index'
    resources :users
  end

  #加上錯誤頁面導向 如需處理其他新的錯誤頁面 方便再擴增
  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true
  validate_email = /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  validates :email, presence: true, format: { with: validate_email }
  validates_uniqueness_of :email, :message => "你的 Email 重複了"
  validates :password, presence: true, length: { minimum: 6 }
  before_destroy :final_admin

  has_many :tasks, dependent: :destroy
  
  has_secure_password

  #檢查使用者身份是不是admin 如果admin剩最後一個 無法被刪除
  def final_admin
    return unless self.role == 'admin'
      if User.where(role: 'admin').count == 1
        errors.add(:base, I18n.t('admin.final_admin')) 
        throw(:abort) 
        # halt msg: I18n.t('admin.final_admin')
      end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :find_user, only: %i[edit update show destroy]
  before_action :search_user_tasks, only: [:show]

  def index
    @users = User.page(params[:page]).per(20)
  end
  
  def show
    @tasks = @q.result(distinct: true).page(params[:page]).per(10)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: t('user.signup_t')
    else 
      render :new
    end
  end

  def edit
  end
  #管理者可以在頁面修改會員身份
  def update
    if admin?
      @user.update_columns(filter_params)
      redirect_to admin_users_path, notice: t('user.edit_t')
    else  
      render :edit, notice: t('user.edit_f')
    end
  end

  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: t('admin.destroy.notice')
    else  
      redirect_to admin_users_path, notice: "#{@user.errors[:base]}"
    end
  end

  private

  def find_user
    @user = User.find_by(id: params[:id])
    redirect_to admin_root_path if @user.nil?
  end

  def search_user_tasks
    @q = Task.includes(:user).where(users: {id: @user.id}).ransack(params[:q])
  end

  def user_params
    params.require(:user).permit(:username, :email, :password, :role)
  end
  #因修改傳進來的資料會是一個object 所以要用to_h轉成hash
  def filter_params
    (user_params.select { |k, v| !v.blank? }).to_h
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: %i[show edit update]
  before_action :find_user, only: [:show, :edit, :update]
  before_action :check_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login @user
      redirect_to root_path, notice: t('views.user.create')
    else 
      render :new
    end
  end

  
  def show
  end
  
  def edit
  end
  
  def update
    if @user.update(filter_params)
      redirect_to user_path(@user), notice: t('user.edit_t')
    else  
      render :edit, notice: t('user.edit_f')
    end
  end
  
  def destroy

  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :role)
  end

  def find_user
    @user = User.find_by(id: params[:id])
  end

  def check_user
    redirect_to root_path unless @user
  end

  def filter_params
    user_params.select { |k, v| !v.blank? }
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def identity(role)
    case role
    when "menber"
      t('admin.menber')
    when "admin"
      t('admin.admin')
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-4">
    <div class="card mt-5">
      <div class="card-header text-center">
        <%= t('user.edit_user')%>
      </div>
      <div class="card-body">
        <%= simple_form_for [:admin, @user] do |f| %>
          <div class="form-inputs">
            <%= f.input :username,label: t('views.user.username'), required: false, autofocus: true %>
            <%= f.input :role, label: t('admin.identity'), collection: [:menber, :admin] %>
          </div>

          <div class="form-actions">
            <%= f.button :submit, t("views.submit_btn"), class:'btn btn-primary form-control' %>
          </div>
        <% end %>

      </div>
      <div class="card-footer text-muted">
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<h1 class="mx-auto" style="width: 200px;"><%= t('admin.user.all_menber') %><h1>
<%= link_to t('user.create'), new_admin_user_path, class: "btn btn-primary btn-lg btn-block"%>
<table class="table mt-3">
  <thead class="">
    <tr>
      <th scope="col"><%= t('views.user.username') %></th>
      <th sope="col"><%= t('views.user.email') %></th>
      <th sope="col"><%= t('views.user.tasks_count') %></th>
      <th sope="col"><%= t('admin.identity') %></th>
      <th class="user-table-control" scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %> 
    <tr>
      <td ><%= link_to user.username, admin_user_path(user) %></td>
      <td ><%= user.email %></td>
      <td ><%= user.tasks_count %></td>
      <td ><%= user.role %></td>
      <td class="user-table-control">
        <%= link_to t('user.edit'), edit_admin_user_path(user), class: 'btn btn-outline-secondary btn-sm btn-edit' %>
        <%= link_to t('user.delete'), admin_user_path(user),data: {:confirm => t('admin.delete_msg') }, method: :delete, class:"btn btn-outline-secondary btn-sm btn-delete" %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
<div class="row justify-content-md-center">
    <div class="col-4">
      <div class="card mt-5">
        <div class="card-header text-center">
          <%= t('user.signup') %>
        </div>
        <div class="card-body">
          <%= simple_form_for @user do |f| %>
            <%= f.error_notification %>
            <div class="form-inputs">
              <%= f.input :username,label: t('views.user.username'), required: false, autofocus: true %>
              <%= f.input :email,label: t('views.user.email'), placeholder: "example@gmail.com", required: false, autofocus: true %>
              <%= f.input :password,label: t('views.user.password'), placeholder: "minimum 6", required: false %>
            </div>

            <div class="form-actions">
              <%= f.button :submit, t("views.user.sign_up"), class:'btn btn-primary form-control' %>
            </div>
          <% end %>

        </div>
        <div class="card-footer text-muted">
        </div>
      </div>
    </div>
  </div>

app/views/admin/users/show.html.erb
<div id="admin_user_name">
<h1><%= @user.username %></h1>
</div>
<div class="row justify-content-md-center" id="admin_user_showpage" >
  <div class="col-4">
    <div class="card mt-5">
      <div class="card-header text-center">
        <%= t('user.profile') %>
      </div>
      <div class="card-body">
        <p><%= t('views.user.username') %>: <%= @user.username %></p>          
        <p><%= t('views.user.email') %>: <%= @user.email %></p>          
      </div>
    </div>
  </div>
</div>
<table class="table table-hover">
  <thead class="thead-dark">
    <tr>
      <td scope="col"><%= t('views.tasks.title') %></td>
      <td scope="col"><%= t('views.tasks.username') %></td>
      <td scope="col"><%= t('views.tasks.date') %></td>
      <td scope="col"><%= t('views.tasks.state') %></td>
      <td scope="col"><%= t('views.tasks.priority') %></td>
    </tr>
  </thead>
  <tbody>
  <% @tasks.each do |task| %>
    <tr>
      <td scope="row"><%= task.task %></td>
      <td scope="row"><%= task.user.username %></td>
      <td scope="row"><%= (task.deadline).strftime("%Y年%m月 %d日, %H:%M") %></td>
      <td scope="row"><%= task_state(task.state) %></td>
      <td scope="row"><%= task_priority(task.priority) %></td>
      <td scope="row">
      <%= link_to t('views.tasks.edit'), edit_task_path(task), class:"btn btn-outline-warning" %>
      <%= link_to t('views.tasks.show'), task_path(task), class:"btn btn-outline-primary"  %>
      <%= link_to t('views.tasks.delete'), task_path(task), method: "delete", data:{ confirm: t('views.tasks.delete_msg')}, class:"btn btn-outline-danger"  %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div id="back_to_admin_page">
<%= link_to t('views.home'), admin_users_path, class:"btn btn-primary btn-lg btn-block" %>
</div>

<%= paginate @tasks, :theme => 'twitter-bootstrap-4'  %>