config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "tasks#index"
  # get 'sessions/new'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  #使用 collection 要對複數資料做操作
  resources :tasks do
    collection do
      get :search
    end
  end

  resources :users, controller: 'users'
  namespace :admin do
    root 'user#index'
    resources :users
  end

  #加上錯誤頁面導向 如需處理其他新的錯誤頁面 方便再擴增
  %w(404 422 500).each do |code|
    get code, to: "errors#show", code: code
  end
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class="navbar-nav">
  <% if current_user %>
  <li class="nav-item dropdown">
    <%= link_to current_user.username, user_path(current_user), class: 'nav-link dropdown-toggle', data:{ toggle:'dropdown'} %>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to t('user.profile'),  user_path(current_user), class: 'dropdown-item' %>
        <%= link_to t('user.edit'),  edit_user_path(current_user), class: 'dropdown-item' %>
        <%= link_to t('admin.back_end'), admin_users_path, class: 'dropdown-item' %>
        <%= link_to t('admin.front_end'), root_path, class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to t('user.logout'), logout_path, method: "delete", class: 'dropdown-item' %>
      </div>
  </li>
  <% else %>
    <li class="nav-item">
      <%= link_to t('views.user_signin'), login_path, class:'nav-link' %>
    </li>
  <% end %>
  </ul>
  
  <div class="container">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      </button>
      <%= notice %>
    </div>
  </div>
  

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <ul class="navbar-nav">
  <% if current_user %>
  <li class="nav-item dropdown">
    <%= link_to current_user.username, user_path(current_user), class: 'nav-link dropdown-toggle', data:{ toggle:'dropdown'} %>
      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        <%= link_to t('user.profile'),  user_path(current_user), class: 'dropdown-item' %>
        <%= link_to t('user.edit'),  edit_user_path(current_user), class: 'dropdown-item' %>
        <div class="dropdown-divider"></div>
        <%= link_to t('user.logout'), logout_path, method: "delete", class: 'dropdown-item' %>
        <% if admin? %>
        <%= link_to "管理者介面", admin_users_path, class: 'dropdown-item' %>
        <% end %>
      </div>
  </li>
  <% else %>
    <li class="nav-item">
      <%= link_to t('views.user_signin'), login_path, class:'nav-link' %>
    </li>
  <% end %>
  </ul>
  
  <div class="container">
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      </button>
      <%= notice %>
    </div>
  </div>
  

  <div class="container">
    <%= yield %>
  </div>

  <script>

    $(document).on('turbolinks:load', function(){
      $( "#task_tag_items" ).select2({
        language: "zh-TW"
      });
      $("#task_tag_items").select2({
        tags: true,
        createTag: function(params){
          var term = $.trim(params.term);
          if(term === '') {
            return null;
        }
          return {
            id: term,
            text: term,
            newTag: true
          }
        }
      })
    });
  </script>
  </body>
</html>